reporting_market:
  - Name: "Chicago"
    id: 85940195
  - Name: "New York"
    id: 85977539
  - Name: "Washington"
    id: 85931779
  - Name: "Toronto"
    id: 101735835
  - Name: "Boston"
    id: 85950361
  - Name: "Los Angeles"
    id: 85923517
  - Name: "Seattle"
    id: 101730401
    manual_neighbourhoods:
      - 420783249
  - Name: "San Francisco"
    id: 85922583
    alt_shape: "alt-mapzen"
  - Name: "Miami"
    id: 85933669
  - Name: "Houston"
    id: 101725629
  - Name: "Nashville"
    id: 101723183
  - Name: "Milwaukee"
    id: 1259598703
  - Name: "Minneapolis"
    id: 1729436991
  - Name: "Indianapolis"
    id: 1260310291
  - Name: "Detroit"
    id: 85951091
