"""empty message

Revision ID: 072cdd676d12
Revises: 
Create Date: 2024-09-02 18:42:56.086548

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2



# revision identifiers, used by Alembic.
revision = '072cdd676d12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shapefile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bbox', sa.String(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='NONE', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shapefile'))
    )
    with op.batch_alter_table('shapefile', schema=None) as batch_op:
        batch_op.create_index('idx_shapefile_geometry', ['geometry'], unique=False, postgresql_using='gist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shapefile', schema=None) as batch_op:
        batch_op.drop_index('idx_shapefile_geometry', postgresql_using='gist')

    op.drop_table('shapefile')
    # ### end Alembic commands ###
