"""empty message

Revision ID: 07e277b08ed3
Revises: 173b35ad8c51
Create Date: 2024-08-08 19:30:29.764994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e277b08ed3'
down_revision = '173b35ad8c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.drop_column('label')

    # ### end Alembic commands ###
