"""empty message

Revision ID: 0bd0e72a1836
Revises: ceefa0c13b57
Create Date: 2024-08-11 21:59:16.512391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd0e72a1836'
down_revision = 'ceefa0c13b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimension_tags',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dimension_name', sa.String(), nullable=False),
    sa.Column('primary_tag', sa.String(), nullable=True),
    sa.Column('secondary_tag', sa.String(), nullable=True),
    sa.Column('data_group', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dimension_name'], ['dimension.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.drop_column('secondary_tag')
        batch_op.drop_column('primary_tag')
        batch_op.drop_column('data_group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_group', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('primary_tag', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('secondary_tag', sa.VARCHAR(), nullable=True))

    op.drop_table('dimension_tags')
    # ### end Alembic commands ###
