"""empty message

Revision ID: 0d46474c9d5c
Revises: 775900d406b1
Create Date: 2024-08-11 22:52:47.657425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d46474c9d5c'
down_revision = '775900d406b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.drop_column('queryableGranularities')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queryableGranularities', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
