"""empty message

Revision ID: 173b35ad8c51
Revises: 
Create Date: 2024-08-08 18:58:50.996970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173b35ad8c51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimension',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('primary_tag', sa.String(), nullable=True),
    sa.Column('secondary_tag', sa.String(), nullable=True),
    sa.Column('data_group', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dimension')
    # ### end Alembic commands ###
