"""empty message

Revision ID: 4226d05c826e
Revises: 64fa32b6f314
Create Date: 2024-08-13 01:00:38.214893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4226d05c826e'
down_revision = '64fa32b6f314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_metric'))
    )
    op.create_table('metric_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=True),
    sa.Column('metric_category', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['name'], ['metric.name'], name=op.f('fk_metric_tags_name_metric')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_tags')),
    sa.UniqueConstraint('name', name='fk_unique_constraint_metric'),
    sa.UniqueConstraint('name', name=op.f('uq_metric_tags_name'))
    )
    with op.batch_alter_table('dimension_tags', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_dimension_tags_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimension_tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_dimension_tags_name'), type_='unique')

    op.drop_table('metric_tags')
    op.drop_table('metric')
    # ### end Alembic commands ###
