"""empty message

Revision ID: 4917f1d8a2d6
Revises: 
Create Date: 2024-09-18 14:14:22.429998

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '4917f1d8a2d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('shapefile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('placetype', sa.String(), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=False),
    sa.Column('geojson', sa.String(), nullable=False),
    sa.Column('geometry', Geometry(geometry_type='NONE', spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shapefile', schema=None) as batch_op:
        batch_op.create_geospatial_index('idx_shapefile_geometry', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shapefile', schema=None) as batch_op:
        batch_op.drop_geospatial_index('idx_shapefile_geometry', postgresql_using='gist', column_name='geometry')

    op.drop_geospatial_table('shapefile')
    # ### end Alembic commands ###
