"""empty message

Revision ID: 52ecd32bde76
Revises: d9e6342a0d72
Create Date: 2024-09-20 10:08:17.801132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ecd32bde76'
down_revision = 'd9e6342a0d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shapefile', schema=None) as batch_op:
        batch_op.create_geospatial_index('idx_shapefile_geometry', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shapefile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.drop_geospatial_index('idx_shapefile_geometry', postgresql_using='gist', column_name='geometry')

    # ### end Alembic commands ###
