"""empty message

Revision ID: 64fa32b6f314
Revises: 32600f2bda2b
Create Date: 2024-08-12 23:28:35.206346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64fa32b6f314'
down_revision = '32600f2bda2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimension_tags', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_dimension_tags_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimension_tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_dimension_tags_name'), type_='unique')

    # ### end Alembic commands ###
