"""empty message

Revision ID: 775900d406b1
Revises: 0bd0e72a1836
Create Date: 2024-08-11 22:50:43.895687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775900d406b1'
down_revision = '0bd0e72a1836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queryableGranularities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('qualifiedName', sa.String(), nullable=True))
        batch_op.drop_column('qualified_name')
        batch_op.drop_column('queryable_granularities')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queryable_granularities', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('qualified_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('qualifiedName')
        batch_op.drop_column('queryableGranularities')

    # ### end Alembic commands ###
