"""empty message

Revision ID: 922fd34c7117
Revises: 343e63da36e8
Create Date: 2024-08-11 21:48:00.681791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922fd34c7117'
down_revision = '343e63da36e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimension_tags',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('primary_tag', sa.String(), nullable=True),
    sa.Column('secondary_tag', sa.String(), nullable=True),
    sa.Column('data_group', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('queryable_granularities', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('qualified_name', sa.String(), nullable=True))
        batch_op.drop_column('data_group')
        batch_op.drop_column('secondary_tag')
        batch_op.drop_column('primary_tag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_tag', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('secondary_tag', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('data_group', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('qualified_name')
        batch_op.drop_column('queryable_granularities')
        batch_op.drop_column('description')

    op.drop_table('dimension_tags')
    # ### end Alembic commands ###
