"""empty message

Revision ID: b9739f24260c
Revises: 
Create Date: 2024-09-20 10:06:49.827456

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = 'b9739f24260c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('shapefile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placetype', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bbox', sa.String(), nullable=False),
    sa.Column('geometry', Geometry(spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shapefile', schema=None) as batch_op:
        batch_op.create_geospatial_index('idx_shapefile_geometry', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shapefile', schema=None) as batch_op:
        batch_op.drop_geospatial_index('idx_shapefile_geometry', postgresql_using='gist', column_name='geometry')

    op.drop_geospatial_table('shapefile')
    # ### end Alembic commands ###
