"""empty message

Revision ID: ceefa0c13b57
Revises: 922fd34c7117
Create Date: 2024-08-11 21:50:41.679922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceefa0c13b57'
down_revision = '922fd34c7117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dimension_tags')
    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_tag', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('secondary_tag', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('data_group', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.drop_column('data_group')
        batch_op.drop_column('secondary_tag')
        batch_op.drop_column('primary_tag')

    op.create_table('dimension_tags',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('primary_tag', sa.VARCHAR(), nullable=True),
    sa.Column('secondary_tag', sa.VARCHAR(), nullable=True),
    sa.Column('data_group', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###
