"""empty message

Revision ID: d9e6342a0d72
Revises: b9739f24260c
Create Date: 2024-09-20 10:07:23.864961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e6342a0d72'
down_revision = 'b9739f24260c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_licenses')
    op.drop_table('sql_statements_log')
    op.drop_table('ElementaryGeometries')
    op.drop_table('SpatialIndex')
    op.drop_table('KNN2')
    with op.batch_alter_table('shapefile', schema=None) as batch_op:
        batch_op.create_geospatial_index('idx_shapefile_geometry', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shapefile', schema=None) as batch_op:
        batch_op.drop_geospatial_index('idx_shapefile_geometry', postgresql_using='gist', column_name='geometry')

    op.create_table('KNN2',
    sa.Column('db_prefix', sa.TEXT(), nullable=True),
    sa.Column('f_table_name', sa.TEXT(), nullable=True),
    sa.Column('f_geometry_column', sa.TEXT(), nullable=True),
    sa.Column('ref_geometry', sa.BLOB(), nullable=True),
    sa.Column('radius', sa.DOUBLE(), nullable=True),
    sa.Column('max_items', sa.INTEGER(), nullable=True),
    sa.Column('expand', sa.INTEGER(), nullable=True),
    sa.Column('pos', sa.INTEGER(), nullable=True),
    sa.Column('fid', sa.INTEGER(), nullable=True),
    sa.Column('distance_crs', sa.DOUBLE(), nullable=True),
    sa.Column('distance_m', sa.DOUBLE(), nullable=True)
    )
    op.create_table('SpatialIndex',
    sa.Column('f_table_name', sa.TEXT(), nullable=True),
    sa.Column('f_geometry_column', sa.TEXT(), nullable=True),
    sa.Column('search_frame', sa.BLOB(), nullable=True)
    )
    op.create_table('ElementaryGeometries',
    sa.Column('db_prefix', sa.TEXT(), nullable=True),
    sa.Column('f_table_name', sa.TEXT(), nullable=True),
    sa.Column('f_geometry_column', sa.TEXT(), nullable=True),
    sa.Column('origin_rowid', sa.INTEGER(), nullable=True),
    sa.Column('item_no', sa.INTEGER(), nullable=True),
    sa.Column('geometry', sa.BLOB(), nullable=True)
    )
    op.create_table('sql_statements_log',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('time_start', sa.TIMESTAMP(), server_default=sa.text("'0000-01-01T00:00:00.000Z'"), nullable=False),
    sa.Column('time_end', sa.TIMESTAMP(), server_default=sa.text("'0000-01-01T00:00:00.000Z'"), nullable=False),
    sa.Column('user_agent', sa.TEXT(), nullable=False),
    sa.Column('sql_statement', sa.TEXT(), nullable=False),
    sa.Column('success', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_cause', sa.TEXT(), server_default=sa.text("'ABORTED'"), nullable=False),
    sa.CheckConstraint('success IN (0,1))', name='sqllog_success'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_licenses',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
