"""empty message

Revision ID: fe474964fe2f
Revises: bc5ec7c5b372
Create Date: 2024-09-20 11:11:44.025424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe474964fe2f'
down_revision = 'bc5ec7c5b372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['shapefile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('loality')
    with op.batch_alter_table('shapefile', schema=None) as batch_op:
        batch_op.create_geospatial_index('idx_shapefile_geometry', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shapefile', schema=None) as batch_op:
        batch_op.drop_geospatial_index('idx_shapefile_geometry', postgresql_using='gist', column_name='geometry')

    op.create_table('loality',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['shapefile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('locality')
    # ### end Alembic commands ###
